version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/functions
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install -g firebase-tools
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: cd functions && npm install
      - run:
          name: deploy functions
          command: firebase deploy --only functions --token "$FIREBASE_TOKEN"